### ISSUE TITLE
Maybe push the code now?

### ISSUE THREAD

**Issue by NirantK** [WolfNiu/AutoAugDialogue#1]
Hey, since the paper is out now. I think it'd be great if you could push tot the code here? 

I'm working on an open source project https://github.com/NirantK/antrix - and I'd much rather abandon that if your work is so much better than mine :)

**Comment by WolfNiu** [comment]
Hi NirantK, thank you for the interest. We're still tidying up the codebase. Will push it before or right after the EMNLP conference.
